BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/"

EXERCISE_IMAGES = {
    # ── CHEST ──────────────────────────────────────────────────────────────
    "Bench Press (Barbell)": BASE + "Barbell_Bench_Press_-_Medium_Grip/1.jpg",
    "Bench Press (Dumbbell)": BASE + "Dumbbell_Bench_Press/1.jpg",
    "Bench Press (Smith Machine)": BASE + "Machine_Bench_Press/1.jpg",
    "Incline Bench Press (Barbell)": BASE
    + "Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg",
    "Incline Bench Press (Dumbbell)": BASE + "Hammer_Grip_Incline_DB_Bench_Press/1.jpg",
    "Incline Bench Press (Smith Machine)": BASE
    + "Smith_Machine_Incline_Bench_Press/0.jpg",
    "Decline Bench Press (Barbell)": BASE + "Decline_Barbell_Bench_Press/1.jpg",
    "Decline Bench Press (Dumbbell)": BASE + "Decline_Dumbbell_Bench_Press/1.jpg",
    "Chest Fly (Dumbbell)": BASE + "Dumbbell_Flyes/1.jpg",
    "Chest Fly (Cable)": BASE + "Cable_Crossover/1.jpg",
    "Chest Fly (Machine)": BASE + "Leverage_Chest_Press/1.jpg",
    "Incline Chest Fly (Dumbbell)": BASE + "Incline_Dumbbell_Flyes/1.jpg",
    "Decline Chest Fly (Dumbbell)": BASE + "Decline_Dumbbell_Flyes/1.jpg",
    "Cable Crossover (Cable)": BASE + "Cable_Crossover/1.jpg",
    "Chest Press (Machine)": BASE + "Leverage_Chest_Press/1.jpg",
    "Dumbbell Pullover (Dumbbell)": BASE + "Bent-Arm_Dumbbell_Pullover/1.jpg",
    "Push Up (Bodyweight)": BASE + "Decline_Push-Up/1.jpg",
    "Push Up (Weighted)": BASE + "Decline_Push-Up/1.jpg",
    "Diamond Push Up (Bodyweight)": BASE + "Close-Grip_Push-Up_off_of_a_Dumbbell/1.jpg",
    # ── TRICEPS ────────────────────────────────────────────────────────────
    "Dips (Bodyweight)": BASE + "Dips_-_Triceps_Version/1.jpg",
    "Dips (Weighted)": BASE + "Dips_-_Triceps_Version/1.jpg",
    "Seated Dip (Machine)": BASE + "Dip_Machine/1.jpg",
    "Bench Dip (Bodyweight)": BASE + "Bench_Dips/1.jpg",
    "Skull Crusher (Barbell)": BASE + "Decline_Close-Grip_Bench_To_Skull_Crusher/1.jpg",
    "Skull Crusher (Dumbbell)": BASE + "Lying_Dumbbell_Tricep_Extension/1.jpg",
    "Tricep Pushdown (Cable)": BASE + "Triceps_Pushdown/1.jpg",
    "Rope Pushdown (Cable)": BASE + "Triceps_Pushdown_-_Rope_Attachment/1.jpg",
    "Tricep Kickback (Dumbbell)": BASE + "Tricep_Dumbbell_Kickback/1.jpg",
    "Overhead Extension (Cable)": BASE + "Triceps_Overhead_Extension_with_Rope/1.jpg",
    "Overhead Extension (Dumbbell)": BASE + "Lying_Dumbbell_Tricep_Extension/1.jpg",
    "Close Grip Bench Press (Barbell)": BASE + "Close-Grip_Barbell_Bench_Press/1.jpg",
    # ── BACK ───────────────────────────────────────────────────────────────
    "Bent Over Row (Barbell)": BASE + "Bent_Over_Barbell_Row/1.jpg",
    "Bent Over Row (Dumbbell)": BASE + "Bent_Over_Two-Dumbbell_Row/1.jpg",
    "Bent Over Row (Smith Machine)": BASE + "Bent_Over_Barbell_Row/1.jpg",
    "Single-Arm Dumbbell Row (Dumbbell)": BASE + "One-Arm_Dumbbell_Row/1.jpg",
    "Cable Row (Cable)": BASE + "Seated_Cable_Rows/1.jpg",
    "Pullover (Machine)": BASE + "Bent-Arm_Dumbbell_Pullover/1.jpg",
    "Seated Row (Machine)": BASE + "Seated_Cable_Rows/1.jpg",
    "T-Bar Row (Barbell)": BASE + "T-Bar_Row_with_Handle/1.jpg",
    "Pendlay Row (Barbell)": BASE + "Bent_Over_Barbell_Row/1.jpg",
    "Pull Up (Bodyweight)": BASE + "Band_Assisted_Pull-Up/1.jpg",
    "Pull Up (Weighted)": BASE + "Band_Assisted_Pull-Up/1.jpg",
    "Pull Up (Machine)": BASE + "Band_Assisted_Pull-Up/1.jpg",
    "Chin Up (Bodyweight)": BASE + "Close-Grip_Front_Lat_Pulldown/1.jpg",
    "Chin Up (Weighted)": BASE + "Close-Grip_Front_Lat_Pulldown/1.jpg",
    "Lat Pulldown (Cable)": BASE + "Wide-Grip_Lat_Pulldown/1.jpg",
    "Lat Pulldown (Machine)": BASE + "Wide-Grip_Lat_Pulldown/1.jpg",
    "Straight Arm Pulldown (Cable)": BASE + "Straight-Arm_Pulldown/1.jpg",
    "Single Arm Cable Row (Cable)": BASE + "One-Arm_Dumbbell_Row/1.jpg",
    "Chest Supported Row (Dumbbell)": BASE + "Bent_Over_Two-Dumbbell_Row/1.jpg",
    "Chest Supported Row (Machine)": BASE + "Dumbbell_Incline_Row/1.jpg",
    "Hyperextension (Machine)": BASE + "Reverse_Hyperextension/1.jpg",
    "Face Pull (Cable)": BASE + "Face_Pull/1.jpg",
    "Deadlift (Barbell)": BASE + "Barbell_Deadlift/1.jpg",
    "Romanian Deadlift (Barbell)": BASE + "Romanian_Deadlift/1.jpg",
    "Romanian Deadlift (Dumbbell)": BASE + "Stiff-Legged_Dumbbell_Deadlift/1.jpg",
    "Romanian Deadlift (Smith Machine)": BASE + "Romanian_Deadlift/1.jpg",
    "Single-Leg Romanian Deadlift (Dumbbell)": BASE
    + "Stiff-Legged_Dumbbell_Deadlift/0.jpg",
    "Single-Leg Romanian Deadlift (Barbell)": BASE + "Romanian_Deadlift/1.jpg",
    "Sumo Deadlift (Barbell)": BASE + "Sumo_Deadlift/1.jpg",
    "Good Morning (Barbell)": BASE + "Good_Morning/1.jpg",
    "Back Extension (Bodyweight)": BASE + "Hyperextensions_Back_Extensions/1.jpg",
    "Inverted Row (Bodyweight)": BASE + "Inverted_Row/1.jpg",
    "Meadows Row (Barbell)": BASE + "One-Arm_Long_Bar_Row/1.jpg",
    # ── SHOULDERS ──────────────────────────────────────────────────────────
    "Overhead Press (Barbell)": BASE + "Barbell_Shoulder_Press/1.jpg",
    "Overhead Press (Dumbbell)": BASE + "Dumbbell_Shoulder_Press/1.jpg",
    "Overhead Press (Smith Machine)": BASE
    + "Smith_Machine_Overhead_Shoulder_Press/0.jpg",
    "Overhead Press (Machine)": BASE + "Smith_Machine_Overhead_Shoulder_Press/1.jpg",
    "Cuban Press (Dumbbell)": BASE + "Cuban_Press/1.jpg",
    "Arnold Press (Dumbbell)": BASE + "Arnold_Dumbbell_Press/1.jpg",
    "Landmine Press (Barbell)": BASE + "Landmine_180s/1.jpg",
    "Lateral Raise (Dumbbell)": BASE + "Side_Lateral_Raise/1.jpg",
    "Lateral Raise (Cable)": BASE + "Cable_Seated_Lateral_Raise/1.jpg",
    "Lateral Raise (Machine)": BASE + "Cable_Seated_Lateral_Raise/1.jpg",
    "Front Raise (Dumbbell)": BASE + "Front_Dumbbell_Raise/1.jpg",
    "Front Raise (Barbell)": BASE + "Front_Plate_Raise/1.jpg",
    "Front Raise (Cable)": BASE + "Front_Cable_Raise/1.jpg",
    "Rear Delt Fly (Dumbbell)": BASE + "Lying_Rear_Delt_Raise/1.jpg",
    "Rear Delt Fly (Cable)": BASE + "Cable_Rear_Delt_Fly/1.jpg",
    "Rear Delt Fly (Machine)": BASE + "Lying_Rear_Delt_Raise/1.jpg",
    "Upright Row (Barbell)": BASE + "Upright_Barbell_Row/1.jpg",
    "Upright Row (Dumbbell)": BASE + "Dumbbell_One-Arm_Upright_Row/1.jpg",
    "Upright Row (Cable)": BASE + "Upright_Cable_Row/1.jpg",
    "Shrug (Barbell)": BASE + "Barbell_Shrug/1.jpg",
    "Shrug (Dumbbell)": BASE + "Dumbbell_Shrug/1.jpg",
    "Shrug (Cable)": BASE + "Cable_Shrugs/1.jpg",
    # ── BICEPS ─────────────────────────────────────────────────────────────
    "Bicep Curl (Barbell)": BASE + "Barbell_Curl/1.jpg",
    "Bicep Curl (Dumbbell)": BASE + "Dumbbell_Bicep_Curl/1.jpg",
    "Bicep Curl (Cable)": BASE + "Standing_Biceps_Cable_Curl/1.jpg",
    "Bicep Curl (Machine)": BASE + "Machine_Bicep_Curl/1.jpg",
    "Bayesian Curl (Cable)": BASE + "Standing_Biceps_Cable_Curl/1.jpg",
    "EZ Bar Curl (Barbell)": BASE + "Close-Grip_EZ_Bar_Curl/1.jpg",
    "Hammer Curl (Dumbbell)": BASE + "Hammer_Curls/1.jpg",
    "Hammer Curl (Cable)": BASE + "Cable_Hammer_Curls_-_Rope_Attachment/1.jpg",
    "Preacher Curl (Barbell)": BASE + "Preacher_Curl/1.jpg",
    "Preacher Curl (Dumbbell)": BASE + "Zottman_Preacher_Curl/1.jpg",
    "Preacher Curl (Machine)": BASE + "Machine_Preacher_Curls/1.jpg",
    "Concentration Curl (Dumbbell)": BASE + "Standing_Concentration_Curl/1.jpg",
    "Incline Dumbbell Curl (Dumbbell)": BASE + "Incline_Dumbbell_Curl/1.jpg",
    "Spider Curl (Dumbbell)": BASE + "Spider_Curl/1.jpg",
    "Spider Curl (Barbell)": BASE + "Spider_Curl/1.jpg",
    "21s (Barbell)": BASE + "Barbell_Curl/1.jpg",
    "Reverse Curl (Barbell)": BASE + "Reverse_Barbell_Curl/1.jpg",
    "Reverse Curl (Dumbbell)": BASE + "Standing_Dumbbell_Reverse_Curl/1.jpg",
    "Reverse EZ Bar Curl (Barbell)": BASE + "Reverse_Barbell_Curl/1.jpg",
    # ── LEGS ───────────────────────────────────────────────────────────────
    "Squat (Barbell)": BASE + "Barbell_Full_Squat/1.jpg",
    "Squat (Smith Machine)": BASE + "Smith_Machine_Squat/1.jpg",
    "Squat (Bodyweight)": BASE + "Bodyweight_Squat/1.jpg",
    "Front Squat (Barbell)": BASE + "Front_Barbell_Squat/1.jpg",
    "Pistol Squat (Bodyweight)": BASE + "Bodyweight_Squat/1.jpg",
    "Goblet Squat (Dumbbell)": BASE + "Dumbbell_Squat/1.jpg",
    "Goblet Squat (Kettlebell)": BASE + "Dumbbell_Squat/1.jpg",
    "Hack Squat (Machine)": BASE + "Hack_Squat/1.jpg",
    "Leg Press (Machine)": BASE + "Leg_Press/1.jpg",
    "Leg Extension (Machine)": BASE + "Single-Leg_Leg_Extension/1.jpg",
    "Lying Leg Curl (Machine)": BASE + "Lying_Leg_Curls/1.jpg",
    "Seated Leg Curl (Machine)": BASE + "Seated_Leg_Curl/1.jpg",
    "Standing Leg Curl (Machine)": BASE + "Standing_Leg_Curl/1.jpg",
    "Nordic Curl (Bodyweight)": BASE + "Lower_Back_Curl/1.jpg",
    "Single Leg Press (Machine)": BASE + "Leg_Press/1.jpg",
    "Lunge (Barbell)": BASE + "Barbell_Lunge/1.jpg",
    "Lunge (Dumbbell)": BASE + "Dumbbell_Lunges/1.jpg",
    "Lunge (Bodyweight)": BASE + "Bodyweight_Walking_Lunge/1.jpg",
    "Reverse Lunge (Bodyweight)": BASE + "Crossover_Reverse_Lunge/1.jpg",
    "Reverse Lunge (Dumbbell)": BASE + "Dumbbell_Lunges/1.jpg",
    "Walking Lunge (Bodyweight)": BASE + "Bodyweight_Walking_Lunge/1.jpg",
    "Walking Lunge (Dumbbell)": BASE + "Dumbbell_Lunges/1.jpg",
    "Bulgarian Split Squat (Bodyweight)": BASE + "Split_Squats/1.jpg",
    "Bulgarian Split Squat (Dumbbell)": BASE + "Split_Squat_with_Dumbbells/1.jpg",
    "Bulgarian Split Squat (Barbell)": BASE + "Barbell_Side_Split_Squat/1.jpg",
    "Split Squat (Barbell)": BASE + "Barbell_Side_Split_Squat/1.jpg",
    "Step Up (Bodyweight)": BASE + "Dumbbell_Step_Ups/1.jpg",
    "Step Up (Dumbbell)": BASE + "Dumbbell_Step_Ups/1.jpg",
    "Hip Thrust (Barbell)": BASE + "Barbell_Hip_Thrust/1.jpg",
    "Hip Thrust (Dumbbell)": BASE + "Barbell_Hip_Thrust/1.jpg",
    "Hip Thrust (Machine)": BASE + "Smith_Machine_Hip_Raise/1.jpg",
    "Glute Bridge (Bodyweight)": BASE + "Single_Leg_Glute_Bridge/1.jpg",
    "Cable Kickback (Cable)": BASE + "One-Legged_Cable_Kickback/1.jpg",
    "Standing Calf Raise (Machine)": BASE + "Standing_Calf_Raises/1.jpg",
    "Standing Calf Raise (Barbell)": BASE + "Rocking_Standing_Calf_Raise/1.jpg",
    "Standing Calf Raise (Smith Machine)": BASE + "Rocking_Standing_Calf_Raise/1.jpg",
    "Seated Calf Raise (Machine)": BASE + "Seated_Calf_Raise/1.jpg",
    "Calf Raise (Bodyweight)": BASE + "Standing_Calf_Raises/1.jpg",
    "Calf Raise (Dumbbell)": BASE + "Calf_Raise_On_A_Dumbbell/1.jpg",
    "Hip Abduction (Machine)": BASE + "Band_Hip_Adductions/1.jpg",
    "Hip Adduction (Machine)": BASE + "Cable_Hip_Adduction/1.jpg",
    # ── CORE ───────────────────────────────────────────────────────────────
    "Crunch (Bodyweight)": BASE + "Tuck_Crunch/1.jpg",
    "Crunch (Cable)": BASE + "Rope_Crunch/1.jpg",
    "Bicycle Crunch (Bodyweight)": BASE + "Air_Bike/1.jpg",
    "Reverse Crunch (Bodyweight)": BASE + "Reverse_Crunch/1.jpg",
    "Superman (Bodyweight)": BASE + "Superman/1.jpg",
    "Hanging Knee Raise (Bodyweight)": BASE + "Hanging_Leg_Raise/1.jpg",
    "Hanging Leg Raise (Bodyweight)": BASE + "Hanging_Leg_Raise/1.jpg",
    "Plank (Bodyweight)": BASE + "Plank/1.jpg",
    "Side Plank (Bodyweight)": BASE + "Oblique_Crunches_-_On_The_Floor/1.jpg",
    "Bird Dog (Bodyweight)": BASE + "Superman/1.jpg",
    "Toes To Bar (Bodyweight)": BASE + "Hanging_Leg_Raise/1.jpg",
    "Leg Raise (Bodyweight)": BASE + "Hanging_Leg_Raise/1.jpg",
    "Ab Wheel (Machine)": BASE + "Ab_Crunch_Machine/1.jpg",
    "Russian Twist (Bodyweight)": BASE + "Russian_Twist/1.jpg",
    "Russian Twist (Medicine Ball)": BASE + "Medicine_Ball_Full_Twist/1.jpg",
    "Woodchopper (Cable)": BASE + "Cable_Russian_Twists/1.jpg",
    "Pallof Press (Cable)": BASE + "Pallof_Press/1.jpg",
    "Ab Scissors (Bodyweight)": BASE + "Scissors_Jump/1.jpg",
    "Hollow Hold (Bodyweight)": BASE + "Dead_Bug/1.jpg",
    "Dead Bug (Bodyweight)": BASE + "Dead_Bug/1.jpg",
    "Decline Sit Up (Bodyweight)": BASE + "Decline_Crunch/1.jpg",
    "Mountain Climber (Bodyweight)": BASE + "Mountain_Climbers/1.jpg",
    # ── CARDIO / CONDITIONING ──────────────────────────────────────────────
    "Burpee (Bodyweight)": BASE + "Freehand_Jump_Squat/1.jpg",
    "Jump Squat (Bodyweight)": BASE + "Freehand_Jump_Squat/1.jpg",
    "Box Jump (Bodyweight)": BASE + "Bench_Jump/1.jpg",
    "Rowing Machine (Machine)": BASE + "Elliptical_Trainer/1.jpg",
    "Thruster (Barbell)": BASE + "Clean_and_Press/1.jpg",
    "Thruster (Dumbbell)": BASE + "Dumbbell_Shoulder_Press/1.jpg",
    "Jump Rope (Bodyweight)": BASE + "Fast_Skipping/1.jpg",
    "Battle Ropes (Cable)": BASE + "Battling_Ropes/1.jpg",
    "Wall Sit (Bodyweight)": BASE + "Bodyweight_Squat/1.jpg",
    # ── OLYMPIC / POWER ────────────────────────────────────────────────────
    "Clean and Jerk (Barbell)": BASE + "Clean_and_Jerk/1.jpg",
    "Trap Bar Deadlift (Barbell)": BASE + "Barbell_Deadlift/1.jpg",
    "Power Clean (Barbell)": BASE + "Power_Clean/1.jpg",
    "Hang Clean (Barbell)": BASE + "Hang_Clean/1.jpg",
    "Snatch (Barbell)": BASE + "Snatch/1.jpg",
    # ── KETTLEBELL ─────────────────────────────────────────────────────────
    "Kettlebell Swing (Kettlebell)": BASE + "One-Arm_Kettlebell_Swings/1.jpg",
    "Kettlebell Snatch (Kettlebell)": BASE + "One-Arm_Kettlebell_Snatch/1.jpg",
    "Turkish Get-Up (Kettlebell)": BASE + "Kettlebell_Turkish_Get-Up_Squat_style/1.jpg",
    "Kettlebell Clean (Kettlebell)": BASE + "One-Arm_Kettlebell_Clean/1.jpg",
    "Kettlebell Press (Kettlebell)": BASE + "Kettlebell_Arnold_Press/1.jpg",
    # ── FUNCTIONAL ─────────────────────────────────────────────────────────
    "Farmers Walk (Dumbbell)": BASE + "Farmers_Walk/1.jpg",
    "Farmers Walk (Kettlebell)": BASE + "Farmers_Walk/1.jpg",
    "Renegade Row (Dumbbell)": BASE + "One-Arm_Dumbbell_Row/1.jpg",
    "Sled Push (Machine)": BASE + "Forward_Drag_with_Press/1.jpg",
    "Sled Pull (Machine)": BASE + "Backward_Drag/1.jpg",
    "Wall Ball (Medicine Ball)": BASE + "Medicine_Ball_Scoop_Throw/1.jpg",
}


def seed_exercises(db):
    from models import Exercise

    exercises = [
        # ── CHEST ──────────────────────────────────────────
        {
            "name": "Bench Press",
            "equipment": "Barbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "Triceps,Shoulders",
            "instructions": "Lie flat, lower bar to mid-chest with elbows at 45°, press up",
            "is_global": True,
        },
        {
            "name": "Bench Press",
            "equipment": "Dumbbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "Triceps,Shoulders",
            "instructions": "Press dumbbells up from chest, keep wrists stacked over elbows",
            "is_global": True,
        },
        {
            "name": "Bench Press",
            "equipment": "Smith Machine",
            "primary_muscle": "Chest",
            "secondary_muscles": "Triceps,Shoulders",
            "instructions": "Press bar on smith machine, lower to mid-chest",
            "is_global": True,
        },
        {
            "name": "Incline Bench Press",
            "equipment": "Barbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "Shoulders,Triceps",
            "instructions": "Set bench to 30-45°, press bar from upper chest",
            "is_global": True,
        },
        {
            "name": "Incline Bench Press",
            "equipment": "Dumbbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "Shoulders,Triceps",
            "instructions": "Set bench to 30-45°, press dumbbells from upper chest",
            "is_global": True,
        },
        {
            "name": "Incline Bench Press",
            "equipment": "Smith Machine",
            "primary_muscle": "Chest",
            "secondary_muscles": "Shoulders,Triceps",
            "instructions": "Set bench to 30-45° inside smith machine, press from upper chest",
            "is_global": True,
        },
        {
            "name": "Decline Bench Press",
            "equipment": "Barbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "Triceps",
            "instructions": "Set bench to decline, press bar from lower chest",
            "is_global": True,
        },
        {
            "name": "Decline Bench Press",
            "equipment": "Dumbbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "Triceps",
            "instructions": "Set bench to decline, press dumbbells from lower chest",
            "is_global": True,
        },
        {
            "name": "Chest Fly",
            "equipment": "Dumbbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "",
            "instructions": "Lie flat, lower dumbbells in wide arc keeping slight elbow bend, squeeze at top",
            "is_global": True,
        },
        {
            "name": "Chest Fly",
            "equipment": "Cable",
            "primary_muscle": "Chest",
            "secondary_muscles": "",
            "instructions": "Set cables at chest height, pull together in arc motion, keep slight elbow bend",
            "is_global": True,
        },
        {
            "name": "Incline Chest Fly",
            "equipment": "Dumbbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "",
            "instructions": "Set bench to 30-45°, lower dumbbells in wide arc, focus on upper chest stretch",
            "is_global": True,
        },
        {
            "name": "Decline Chest Fly",
            "equipment": "Dumbbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "",
            "instructions": "Set bench to decline, lower dumbbells in wide arc targeting lower chest",
            "is_global": True,
        },
        {
            "name": "Cable Crossover",
            "equipment": "Cable",
            "primary_muscle": "Chest",
            "secondary_muscles": "",
            "instructions": "Set cables high, pull down and across body in arc motion, squeeze chest at bottom",
            "is_global": True,
        },
        {
            "name": "Chest Press",
            "equipment": "Machine",
            "primary_muscle": "Chest",
            "secondary_muscles": "Triceps",
            "instructions": "Push machine handles forward until arms extended, control the return",
            "is_global": True,
        },
        {
            "name": "Chest Fly",
            "equipment": "Machine",
            "primary_muscle": "Chest",
            "secondary_muscles": "",
            "instructions": "Sit at pec deck machine, bring arms together in arc squeezing chest at center",
            "is_global": True,
        },
        {
            "name": "Dumbbell Pullover",
            "equipment": "Dumbbell",
            "primary_muscle": "Chest",
            "secondary_muscles": "Lats",
            "instructions": "Lie across bench, lower dumbbell behind head in arc keeping slight elbow bend, pull back over chest",
            "is_global": True,
        },
        {
            "name": "Push Up",
            "equipment": "Bodyweight",
            "primary_muscle": "Chest",
            "secondary_muscles": "Triceps,Shoulders",
            "instructions": "Lower chest to ground with body in straight line, push up",
            "is_global": True,
        },
        {
            "name": "Push Up",
            "equipment": "Weighted",
            "primary_muscle": "Chest",
            "secondary_muscles": "Triceps,Shoulders",
            "instructions": "Push up with weight plate on back, keep core tight",
            "is_global": True,
        },
        {
            "name": "Diamond Push Up",
            "equipment": "Bodyweight",
            "primary_muscle": "Triceps",
            "secondary_muscles": "Chest",
            "instructions": "Hands form diamond under chest, lower and push up",
            "is_global": True,
        },
        # ── TRICEPS ────────────────────────────────────────
        {
            "name": "Dips",
            "equipment": "Bodyweight",
            "primary_muscle": "Triceps",
            "secondary_muscles": "Chest,Shoulders",
            "instructions": "Lower body between parallel bars until upper arms parallel to floor, push up",
            "is_global": True,
        },
        {
            "name": "Seated Dip",
            "equipment": "Machine",
            "primary_muscle": "Triceps",
            "secondary_muscles": "Chest",
            "instructions": "Seated dip machine, press handles down until arms fully extended, control the return",
            "is_global": True,
        },
        {
            "name": "Dips",
            "equipment": "Weighted",
            "primary_muscle": "Triceps",
            "secondary_muscles": "Chest,Shoulders",
            "instructions": "Attach weight via belt or hold dumbbell, perform dips with added load",
            "is_global": True,
        },
        {
            "name": "Bench Dip",
            "equipment": "Bodyweight",
            "primary_muscle": "Triceps",
            "secondary_muscles": "Chest",
            "instructions": "Hands on bench behind you, lower hips toward floor, press back up",
            "is_global": True,
        },
        {
            "name": "Skull Crusher",
            "equipment": "Barbell",
            "primary_muscle": "Triceps",
            "secondary_muscles": "",
            "instructions": "Lower bar toward forehead keeping upper arms fixed, extend back up",
            "is_global": True,
        },
        {
            "name": "Skull Crusher",
            "equipment": "Dumbbell",
            "primary_muscle": "Triceps",
            "secondary_muscles": "",
            "instructions": "Lower dumbbells toward forehead keeping upper arms fixed, extend back up",
            "is_global": True,
        },
        {
            "name": "Tricep Pushdown",
            "equipment": "Cable",
            "primary_muscle": "Triceps",
            "secondary_muscles": "",
            "instructions": "Straight bar attachment, elbows fixed at sides, push down until arms fully extended",
            "is_global": True,
        },
        {
            "name": "Rope Pushdown",
            "equipment": "Cable",
            "primary_muscle": "Triceps",
            "secondary_muscles": "",
            "instructions": "Rope attachment, push down and flare wrists out at bottom for full contraction",
            "is_global": True,
        },
        {
            "name": "Tricep Kickback",
            "equipment": "Dumbbell",
            "primary_muscle": "Triceps",
            "secondary_muscles": "",
            "instructions": "Hinge forward, upper arm parallel to floor, extend forearm back until arm straight",
            "is_global": True,
        },
        {
            "name": "Overhead Extension",
            "equipment": "Cable",
            "primary_muscle": "Triceps",
            "secondary_muscles": "",
            "instructions": "Face away from cable, extend rope overhead keeping upper arms by ears",
            "is_global": True,
        },
        {
            "name": "Overhead Extension",
            "equipment": "Dumbbell",
            "primary_muscle": "Triceps",
            "secondary_muscles": "",
            "instructions": "Lower dumbbell behind head keeping upper arms fixed, extend up",
            "is_global": True,
        },
        {
            "name": "Close Grip Bench Press",
            "equipment": "Barbell",
            "primary_muscle": "Triceps",
            "secondary_muscles": "Chest",
            "instructions": "Shoulder-width grip bench press, keep elbows tucked to target triceps",
            "is_global": True,
        },
        # ── BACK ───────────────────────────────────────────
        {
            "name": "Bent Over Row",
            "equipment": "Barbell",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Biceps,Lats",
            "instructions": "Hinge to ~45°, keep back neutral, pull bar to lower chest",
            "is_global": True,
        },
        {
            "name": "Bent Over Row",
            "equipment": "Dumbbell",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps",
            "instructions": "Brace on bench, keep back flat, pull dumbbell to hip",
            "is_global": True,
        },
        {
            "name": "Bent Over Row",
            "equipment": "Smith Machine",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Biceps",
            "instructions": "Hinge under smith bar, pull to lower chest keeping back neutral",
            "is_global": True,
        },
        {
            "name": "Single-Arm Dumbbell Row",
            "equipment": "Dumbbell",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps,Upper Back",
            "instructions": "Brace one hand on bench, pull dumbbell to hip with full range of motion",
            "is_global": True,
        },
        {
            "name": "Cable Row",
            "equipment": "Cable",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Biceps",
            "instructions": "Sit tall at cable station, pull handle to torso, squeeze shoulder blades",
            "is_global": True,
        },
        {
            "name": "Pullover",
            "equipment": "Machine",
            "primary_muscle": "Lats",
            "secondary_muscles": "Chest",
            "instructions": "Pull machine arms from overhead down toward torso, focus on lat contraction throughout",
            "is_global": True,
        },
        {
            "name": "Seated Row",
            "equipment": "Machine",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Biceps",
            "instructions": "Pull machine handles to torso, keep chest against pad",
            "is_global": True,
        },
        {
            "name": "T-Bar Row",
            "equipment": "Barbell",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Biceps",
            "instructions": "Straddle landmine bar, pull to chest keeping back neutral",
            "is_global": True,
        },
        {
            "name": "Pendlay Row",
            "equipment": "Barbell",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Biceps,Lats",
            "instructions": "Bar resets to floor each rep, explosive pull to lower chest from dead stop",
            "is_global": True,
        },
        {
            "name": "Pull Up",
            "equipment": "Bodyweight",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps",
            "instructions": "Overhand grip, pull chin over bar, full dead hang each rep",
            "is_global": True,
        },
        {
            "name": "Pull Up",
            "equipment": "Weighted",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps",
            "instructions": "Attach weight via belt or vest, pull chin over bar with full range",
            "is_global": True,
        },
        {
            "name": "Pull Up",
            "equipment": "Machine",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps",
            "instructions": "Assisted pull up — set counterweight and pull chin over bar",
            "is_global": True,
        },
        {
            "name": "Chin Up",
            "equipment": "Bodyweight",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps",
            "instructions": "Underhand grip, pull chin over bar, full dead hang each rep",
            "is_global": True,
        },
        {
            "name": "Chin Up",
            "equipment": "Weighted",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps",
            "instructions": "Attach weight via belt, underhand grip, pull chin over bar",
            "is_global": True,
        },
        {
            "name": "Lat Pulldown",
            "equipment": "Cable",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps",
            "instructions": "Pull bar to upper chest, lean back slightly, squeeze lats at bottom",
            "is_global": True,
        },
        {
            "name": "Lat Pulldown",
            "equipment": "Machine",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps",
            "instructions": "Pull machine bar to upper chest, control the return",
            "is_global": True,
        },
        {
            "name": "Straight Arm Pulldown",
            "equipment": "Cable",
            "primary_muscle": "Lats",
            "secondary_muscles": "",
            "instructions": "Keep arms straight, pull bar from overhead down to hips, feel lat stretch",
            "is_global": True,
        },
        {
            "name": "Single Arm Cable Row",
            "equipment": "Cable",
            "primary_muscle": "Lats",
            "secondary_muscles": "Upper Back,Biceps",
            "instructions": "Single arm at cable station, pull handle to hip, rotate slightly at top for full contraction",
            "is_global": True,
        },
        {
            "name": "Chest Supported Row",
            "equipment": "Dumbbell",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Lats,Biceps",
            "instructions": "Lie face down on incline bench, row dumbbells up eliminating lower back involvement",
            "is_global": True,
        },
        {
            "name": "Chest Supported Row",
            "equipment": "Machine",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Lats,Biceps",
            "instructions": "Chest against pad, pull handles to torso with no lower back involvement",
            "is_global": True,
        },
        {
            "name": "Hyperextension",
            "equipment": "Machine",
            "primary_muscle": "Lower Back",
            "secondary_muscles": "Glutes,Hamstrings",
            "instructions": "Hips on pad, lower torso toward floor then raise until body is straight, do not hyperextend",
            "is_global": True,
        },
        {
            "name": "Face Pull",
            "equipment": "Cable",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Upper Back",
            "instructions": "Set cable at face height, pull rope to face flaring elbows out, externally rotate",
            "is_global": True,
        },
        {
            "name": "Deadlift",
            "equipment": "Barbell",
            "primary_muscle": "Posterior Chain",
            "secondary_muscles": "Glutes,Hamstrings,Back",
            "instructions": "Brace core, keep back neutral, drive floor away to stand, hinge back down",
            "is_global": True,
        },
        {
            "name": "Romanian Deadlift",
            "equipment": "Barbell",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "Glutes,Lower Back",
            "instructions": "Hinge at hips, lower bar along legs keeping slight knee bend and neutral back",
            "is_global": True,
        },
        {
            "name": "Romanian Deadlift",
            "equipment": "Dumbbell",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "Glutes,Lower Back",
            "instructions": "Hinge at hips, lower dumbbells along legs keeping neutral back",
            "is_global": True,
        },
        {
            "name": "Single-Leg Romanian Deadlift",
            "equipment": "Dumbbell",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "Glutes,Core",
            "instructions": "Balance on one leg, hinge forward lowering dumbbell, keep hips square",
            "is_global": True,
        },
        {
            "name": "Single-Leg Romanian Deadlift",
            "equipment": "Barbell",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "Glutes,Core",
            "instructions": "Balance on one leg, hinge forward with barbell, keep hips level",
            "is_global": True,
        },
        {
            "name": "Sumo Deadlift",
            "equipment": "Barbell",
            "primary_muscle": "Glutes",
            "secondary_muscles": "Hamstrings,Adductors",
            "instructions": "Wide stance with toes out, grip inside legs, keep back neutral and drive hips through",
            "is_global": True,
        },
        {
            "name": "Good Morning",
            "equipment": "Barbell",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "Lower Back",
            "instructions": "Bar on upper back, hinge forward at hips keeping back neutral, return to standing",
            "is_global": True,
        },
        {
            "name": "Back Extension",
            "equipment": "Bodyweight",
            "primary_muscle": "Lower Back",
            "secondary_muscles": "Glutes",
            "instructions": "On hyperextension bench, lower torso then raise until body is straight",
            "is_global": True,
        },
        {
            "name": "Inverted Row",
            "equipment": "Bodyweight",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Biceps,Lats",
            "instructions": "Lie under bar at hip height, grip overhand, pull chest to bar keeping body straight",
            "is_global": True,
        },
        {
            "name": "Meadows Row",
            "equipment": "Barbell",
            "primary_muscle": "Lats",
            "secondary_muscles": "Biceps,Upper Back",
            "instructions": "Stagger stance beside landmine bar, pull end of bar to hip with one arm for deep lat stretch",
            "is_global": True,
        },
        # ── SHOULDERS ──────────────────────────────────────
        {
            "name": "Overhead Press",
            "equipment": "Barbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Triceps",
            "instructions": "Press bar from shoulders to overhead, keep core braced, avoid excessive lean",
            "is_global": True,
        },
        {
            "name": "Cuban Press",
            "equipment": "Dumbbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Upper Back",
            "instructions": "Upright row to 90°, externally rotate forearms up, then press overhead — great for rotator cuff",
            "is_global": True,
        },
        {
            "name": "Overhead Press",
            "equipment": "Dumbbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Triceps",
            "instructions": "Press dumbbells overhead from shoulder height, control the descent",
            "is_global": True,
        },
        {
            "name": "Overhead Press",
            "equipment": "Smith Machine",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Triceps",
            "instructions": "Press bar overhead on smith machine, keep core tight",
            "is_global": True,
        },
        {
            "name": "Overhead Press",
            "equipment": "Machine",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Triceps",
            "instructions": "Push machine handles overhead, control the return",
            "is_global": True,
        },
        {
            "name": "Arnold Press",
            "equipment": "Dumbbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Triceps",
            "instructions": "Start with palms facing you, rotate to press overhead, hits all three delt heads",
            "is_global": True,
        },
        {
            "name": "Landmine Press",
            "equipment": "Barbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Triceps,Core",
            "instructions": "Hold end of landmine bar at shoulder, press up and forward in arc, great for shoulder health",
            "is_global": True,
        },
        {
            "name": "Lateral Raise",
            "equipment": "Dumbbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "",
            "instructions": "Slight elbow bend, raise dumbbells to sides to shoulder height",
            "is_global": True,
        },
        {
            "name": "Lateral Raise",
            "equipment": "Cable",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "",
            "instructions": "Cable at lowest setting, raise to side to shoulder height",
            "is_global": True,
        },
        {
            "name": "Lateral Raise",
            "equipment": "Machine",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "",
            "instructions": "Raise machine arms to sides to shoulder height",
            "is_global": True,
        },
        {
            "name": "Front Raise",
            "equipment": "Dumbbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "",
            "instructions": "Raise dumbbell forward to shoulder height with slight elbow bend",
            "is_global": True,
        },
        {
            "name": "Front Raise",
            "equipment": "Barbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "",
            "instructions": "Raise bar forward to shoulder height, keep core braced",
            "is_global": True,
        },
        {
            "name": "Front Raise",
            "equipment": "Cable",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "",
            "instructions": "Cable at lowest setting, raise handle forward to shoulder height",
            "is_global": True,
        },
        {
            "name": "Rear Delt Fly",
            "equipment": "Dumbbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Upper Back",
            "instructions": "Hinge forward, raise dumbbells to sides keeping slight elbow bend",
            "is_global": True,
        },
        {
            "name": "Rear Delt Fly",
            "equipment": "Cable",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Upper Back",
            "instructions": "Cross cables, pull handles back in reverse fly motion",
            "is_global": True,
        },
        {
            "name": "Rear Delt Fly",
            "equipment": "Machine",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Upper Back",
            "instructions": "Set pec deck to reverse fly, pull handles back squeezing rear delts",
            "is_global": True,
        },
        {
            "name": "Upright Row",
            "equipment": "Barbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Traps",
            "instructions": "Pull bar up along body to chin height, flare elbows above wrists",
            "is_global": True,
        },
        {
            "name": "Upright Row",
            "equipment": "Dumbbell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Traps",
            "instructions": "Pull dumbbells up along body to chin height",
            "is_global": True,
        },
        {
            "name": "Upright Row",
            "equipment": "Cable",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Traps",
            "instructions": "Pull cable bar up along body to chin height",
            "is_global": True,
        },
        {
            "name": "Shrug",
            "equipment": "Barbell",
            "primary_muscle": "Traps",
            "secondary_muscles": "",
            "instructions": "Raise shoulders straight up toward ears, hold briefly, lower with control",
            "is_global": True,
        },
        {
            "name": "Shrug",
            "equipment": "Dumbbell",
            "primary_muscle": "Traps",
            "secondary_muscles": "",
            "instructions": "Raise shoulders straight up toward ears, hold briefly",
            "is_global": True,
        },
        {
            "name": "Shrug",
            "equipment": "Cable",
            "primary_muscle": "Traps",
            "secondary_muscles": "",
            "instructions": "Pull cable upward by raising shoulders toward ears",
            "is_global": True,
        },
        # ── BICEPS ─────────────────────────────────────────
        {
            "name": "Bicep Curl",
            "equipment": "Barbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Elbows pinned at sides, curl bar to shoulders, lower with control",
            "is_global": True,
        },
        {
            "name": "Bicep Curl",
            "equipment": "Dumbbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Elbows pinned at sides, curl dumbbells to shoulders, supinate at top",
            "is_global": True,
        },
        {
            "name": "Bicep Curl",
            "equipment": "Cable",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Elbows fixed, curl cable bar to shoulders for constant tension",
            "is_global": True,
        },
        {
            "name": "Bicep Curl",
            "equipment": "Machine",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Curl machine arm to shoulders, keep upper arms on pad",
            "is_global": True,
        },
        {
            "name": "Bayesian Curl",
            "equipment": "Cable",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Face away from cable with it anchored low behind you, curl handle forward with arm behind body for maximum stretch",
            "is_global": True,
        },
        {
            "name": "EZ Bar Curl",
            "equipment": "Barbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Curl EZ bar to shoulders, angled grip reduces wrist stress",
            "is_global": True,
        },
        {
            "name": "Hammer Curl",
            "equipment": "Dumbbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "Forearms",
            "instructions": "Neutral grip, curl dumbbells to shoulders hitting brachialis and brachioradialis",
            "is_global": True,
        },
        {
            "name": "Hammer Curl",
            "equipment": "Cable",
            "primary_muscle": "Biceps",
            "secondary_muscles": "Forearms",
            "instructions": "Rope attachment, neutral grip curl for constant tension",
            "is_global": True,
        },
        {
            "name": "Preacher Curl",
            "equipment": "Barbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Upper arms on preacher pad, curl bar up, lower with full extension",
            "is_global": True,
        },
        {
            "name": "Preacher Curl",
            "equipment": "Dumbbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Upper arm on preacher pad, curl dumbbell up with full range",
            "is_global": True,
        },
        {
            "name": "Preacher Curl",
            "equipment": "Machine",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Curl on preacher machine, arms supported for strict isolation",
            "is_global": True,
        },
        {
            "name": "Concentration Curl",
            "equipment": "Dumbbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Seated, brace elbow on inner thigh, curl dumbbell up with full squeeze at top",
            "is_global": True,
        },
        {
            "name": "Incline Dumbbell Curl",
            "equipment": "Dumbbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Lie back on incline bench, arms hang straight down, curl up for maximum stretch at bottom",
            "is_global": True,
        },
        {
            "name": "Spider Curl",
            "equipment": "Dumbbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Lie face down on incline bench, arms hang straight, curl up for peak contraction",
            "is_global": True,
        },
        {
            "name": "Spider Curl",
            "equipment": "Barbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "Lie face down on incline bench, curl barbell up for strict peak contraction",
            "is_global": True,
        },
        {
            "name": "21s",
            "equipment": "Barbell",
            "primary_muscle": "Biceps",
            "secondary_muscles": "",
            "instructions": "7 bottom-half reps, 7 top-half reps, 7 full reps back to back",
            "is_global": True,
        },
        {
            "name": "Reverse Curl",
            "equipment": "Barbell",
            "primary_muscle": "Forearms",
            "secondary_muscles": "Biceps",
            "instructions": "Overhand grip curl, targets brachioradialis and forearm extensors",
            "is_global": True,
        },
        {
            "name": "Reverse Curl",
            "equipment": "Dumbbell",
            "primary_muscle": "Forearms",
            "secondary_muscles": "Biceps",
            "instructions": "Overhand grip dumbbell curl, targets brachioradialis and forearm extensors",
            "is_global": True,
        },
        {
            "name": "Reverse EZ Bar Curl",
            "equipment": "Barbell",
            "primary_muscle": "Forearms",
            "secondary_muscles": "Biceps",
            "instructions": "EZ bar overhand grip curl, reduces wrist stress while targeting brachioradialis",
            "is_global": True,
        },
        # ── LEGS ───────────────────────────────────────────
        {
            "name": "Squat",
            "equipment": "Barbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes,Hamstrings",
            "instructions": "Bar on upper back, descend until thighs parallel, drive through heels to stand",
            "is_global": True,
        },
        {
            "name": "Squat",
            "equipment": "Smith Machine",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Feet slightly forward on smith machine, squat to parallel",
            "is_global": True,
        },
        {
            "name": "Squat",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Feet shoulder-width, squat to parallel keeping chest up",
            "is_global": True,
        },
        {
            "name": "Front Squat",
            "equipment": "Barbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Core",
            "instructions": "Bar on front shoulders, elbows high, squat deep keeping torso upright",
            "is_global": True,
        },
        {
            "name": "Pistol Squat",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes,Core",
            "instructions": "Single leg squat with other leg extended forward, lower until thigh is parallel, drive back up",
            "is_global": True,
        },
        {
            "name": "Goblet Squat",
            "equipment": "Dumbbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Hold dumbbell at chest, squat deep keeping elbows inside knees",
            "is_global": True,
        },
        {
            "name": "Goblet Squat",
            "equipment": "Kettlebell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Hold kettlebell at chest, squat deep keeping elbows inside knees",
            "is_global": True,
        },
        {
            "name": "Hack Squat",
            "equipment": "Machine",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Feet on platform, lower until thighs past parallel, drive through heels",
            "is_global": True,
        },
        {
            "name": "Leg Press",
            "equipment": "Machine",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Push platform away with full foot, lower until 90° at knee",
            "is_global": True,
        },
        {
            "name": "Leg Extension",
            "equipment": "Machine",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "",
            "instructions": "Extend legs until straight, hold briefly, lower with control",
            "is_global": True,
        },
        {
            "name": "Lying Leg Curl",
            "equipment": "Machine",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "",
            "instructions": "Curl legs toward glutes, hold at peak contraction, lower with control",
            "is_global": True,
        },
        {
            "name": "Seated Leg Curl",
            "equipment": "Machine",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "",
            "instructions": "Seated position, curl legs under seat, targets hamstrings differently than lying curl",
            "is_global": True,
        },
        {
            "name": "Nordic Curl",
            "equipment": "Bodyweight",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "",
            "instructions": "Kneel with feet anchored, lower torso toward floor under control, pull back up — elite hamstring builder",
            "is_global": True,
        },
        {
            "name": "Romanian Deadlift",
            "equipment": "Smith Machine",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "Glutes,Lower Back",
            "instructions": "Hinge at hips along smith bar keeping slight knee bend and neutral back",
            "is_global": True,
        },
        {
            "name": "Single Leg Press",
            "equipment": "Machine",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "One foot centered on platform, push away, lower until 90° at knee",
            "is_global": True,
        },
        {
            "name": "Lunge",
            "equipment": "Barbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Bar on upper back, step forward until back knee nearly touches floor",
            "is_global": True,
        },
        {
            "name": "Lunge",
            "equipment": "Dumbbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Step forward until back knee nearly touches floor, push back to start",
            "is_global": True,
        },
        {
            "name": "Lunge",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Step forward, lower back knee toward floor, return to standing",
            "is_global": True,
        },
        {
            "name": "Reverse Lunge",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Step backward, lower back knee toward floor, easier on knees than forward lunge",
            "is_global": True,
        },
        {
            "name": "Reverse Lunge",
            "equipment": "Dumbbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Hold dumbbells, step backward lowering back knee toward floor",
            "is_global": True,
        },
        {
            "name": "Walking Lunge",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Alternate forward lunges continuously, keep torso upright",
            "is_global": True,
        },
        {
            "name": "Walking Lunge",
            "equipment": "Dumbbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Alternate forward lunges while holding dumbbells, keep torso upright",
            "is_global": True,
        },
        {
            "name": "Bulgarian Split Squat",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Rear foot elevated on bench, lower front knee toward floor, keep torso upright",
            "is_global": True,
        },
        {
            "name": "Bulgarian Split Squat",
            "equipment": "Dumbbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Rear foot elevated, hold dumbbells, lower until front thigh is parallel",
            "is_global": True,
        },
        {
            "name": "Bulgarian Split Squat",
            "equipment": "Barbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Bar on upper back, rear foot elevated, lower until front thigh is parallel",
            "is_global": True,
        },
        {
            "name": "Step Up",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Step onto elevated surface, drive through heel to stand, lower with control",
            "is_global": True,
        },
        {
            "name": "Step Up",
            "equipment": "Dumbbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Hold dumbbells, step onto elevated surface driving through heel",
            "is_global": True,
        },
        {
            "name": "Hip Thrust",
            "equipment": "Barbell",
            "primary_muscle": "Glutes",
            "secondary_muscles": "Hamstrings",
            "instructions": "Upper back on bench, bar across hips, drive hips to ceiling squeezing glutes",
            "is_global": True,
        },
        {
            "name": "Hip Thrust",
            "equipment": "Dumbbell",
            "primary_muscle": "Glutes",
            "secondary_muscles": "Hamstrings",
            "instructions": "Upper back on bench, dumbbell on hips, drive hips to ceiling",
            "is_global": True,
        },
        {
            "name": "Hip Thrust",
            "equipment": "Machine",
            "primary_muscle": "Glutes",
            "secondary_muscles": "Hamstrings",
            "instructions": "Drive hips forward on hip thrust machine, squeeze glutes at top",
            "is_global": True,
        },
        {
            "name": "Glute Bridge",
            "equipment": "Bodyweight",
            "primary_muscle": "Glutes",
            "secondary_muscles": "Hamstrings",
            "instructions": "Lie on back, drive hips up squeezing glutes, hold briefly at top",
            "is_global": True,
        },
        {
            "name": "Cable Kickback",
            "equipment": "Cable",
            "primary_muscle": "Glutes",
            "secondary_muscles": "",
            "instructions": "Ankle strap on low cable, kick leg straight back squeezing glute at top, keep hips square",
            "is_global": True,
        },
        {
            "name": "Standing Calf Raise",
            "equipment": "Machine",
            "primary_muscle": "Calves",
            "secondary_muscles": "",
            "instructions": "Balls of feet on edge, raise heels as high as possible, lower with control",
            "is_global": True,
        },
        {
            "name": "Standing Calf Raise",
            "equipment": "Barbell",
            "primary_muscle": "Calves",
            "secondary_muscles": "",
            "instructions": "Bar on upper back, balls of feet on edge or flat, raise heels as high as possible",
            "is_global": True,
        },
        {
            "name": "Standing Calf Raise",
            "equipment": "Smith Machine",
            "primary_muscle": "Calves",
            "secondary_muscles": "",
            "instructions": "Bar on upper back in smith machine, balls of feet on edge, raise heels fully",
            "is_global": True,
        },
        {
            "name": "Seated Calf Raise",
            "equipment": "Machine",
            "primary_muscle": "Calves",
            "secondary_muscles": "",
            "instructions": "Seated with weight on knees, raise heels, targets soleus",
            "is_global": True,
        },
        {
            "name": "Calf Raise",
            "equipment": "Bodyweight",
            "primary_muscle": "Calves",
            "secondary_muscles": "",
            "instructions": "Raise up onto toes as high as possible, lower with control",
            "is_global": True,
        },
        {
            "name": "Calf Raise",
            "equipment": "Dumbbell",
            "primary_muscle": "Calves",
            "secondary_muscles": "",
            "instructions": "Single leg on edge of step holding dumbbell, full range of motion",
            "is_global": True,
        },
        {
            "name": "Standing Leg Curl",
            "equipment": "Machine",
            "primary_muscle": "Hamstrings",
            "secondary_muscles": "",
            "instructions": "Stand on machine platform, curl one leg toward glute, keep hips stable",
            "is_global": True,
        },
        {
            "name": "Hip Abduction",
            "equipment": "Machine",
            "primary_muscle": "Abductors",
            "secondary_muscles": "Glutes",
            "instructions": "Seated, push legs outward against pads, control the return",
            "is_global": True,
        },
        {
            "name": "Hip Adduction",
            "equipment": "Machine",
            "primary_muscle": "Adductors",
            "secondary_muscles": "",
            "instructions": "Seated, squeeze legs inward against pads, control the return",
            "is_global": True,
        },
        {
            "name": "Split Squat",
            "equipment": "Barbell",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes",
            "instructions": "Staggered stance with bar on back, both feet on floor — no elevation, lower back knee toward floor",
            "is_global": True,
        },
        # ── CORE ───────────────────────────────────────────
        {
            "name": "Bicycle Crunch",
            "equipment": "Bodyweight",
            "primary_muscle": "Obliques",
            "secondary_muscles": "Abdominals",
            "instructions": "Alternate bringing opposite elbow to knee while extending other leg, continuous pedaling motion",
            "is_global": True,
        },
        {
            "name": "Reverse Crunch",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "",
            "instructions": "Lie flat, pull knees to chest curling hips off floor, lower with control — targets lower abs",
            "is_global": True,
        },
        {
            "name": "Superman",
            "equipment": "Bodyweight",
            "primary_muscle": "Lower Back",
            "secondary_muscles": "Glutes",
            "instructions": "Lie face down, simultaneously raise arms and legs off floor, hold briefly, lower with control",
            "is_global": True,
        },
        {
            "name": "Hanging Knee Raise",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "",
            "instructions": "Dead hang from bar, pull knees to chest keeping core tight, lower with control",
            "is_global": True,
        },
        {
            "name": "Plank",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "Core",
            "instructions": "Forearms on floor, body in straight line, squeeze abs and glutes throughout",
            "is_global": True,
        },
        {
            "name": "Side Plank",
            "equipment": "Bodyweight",
            "primary_muscle": "Obliques",
            "secondary_muscles": "Abdominals",
            "instructions": "One forearm on floor, body straight sideways, hold position",
            "is_global": True,
        },
        {
            "name": "Crunch",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "",
            "instructions": "Feet flat, curl shoulders off ground, do not pull on neck",
            "is_global": True,
        },
        {
            "name": "Bird Dog",
            "equipment": "Bodyweight",
            "primary_muscle": "Core",
            "secondary_muscles": "Lower Back",
            "instructions": "On all fours, extend opposite arm and leg keeping hips level, hold 2-3 seconds, alternate sides",
            "is_global": True,
        },
        {
            "name": "Toes To Bar",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "Core",
            "instructions": "Dead hang from bar, raise straight legs until toes touch bar, lower with control",
            "is_global": True,
        },
        {
            "name": "Crunch",
            "equipment": "Cable",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "",
            "instructions": "Kneel facing cable, rope behind head, crunch elbows toward knees",
            "is_global": True,
        },
        {
            "name": "Hanging Leg Raise",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "",
            "instructions": "Dead hang from bar, raise legs to parallel or higher keeping core tight",
            "is_global": True,
        },
        {
            "name": "Leg Raise",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "",
            "instructions": "Lie flat, raise legs to 90° keeping lower back pressed down",
            "is_global": True,
        },
        {
            "name": "Ab Wheel",
            "equipment": "Machine",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "Core",
            "instructions": "Kneel, roll wheel forward maintaining neutral spine, pull back with abs",
            "is_global": True,
        },
        {
            "name": "Russian Twist",
            "equipment": "Bodyweight",
            "primary_muscle": "Obliques",
            "secondary_muscles": "Abdominals",
            "instructions": "Feet elevated, lean back slightly, rotate torso side to side",
            "is_global": True,
        },
        {
            "name": "Russian Twist",
            "equipment": "Medicine Ball",
            "primary_muscle": "Obliques",
            "secondary_muscles": "Abdominals",
            "instructions": "Hold medicine ball, feet elevated, rotate torso side to side",
            "is_global": True,
        },
        {
            "name": "Woodchopper",
            "equipment": "Cable",
            "primary_muscle": "Obliques",
            "secondary_muscles": "Abdominals,Core",
            "instructions": "Cable high, pull diagonally across body to low opposite side in chopping motion",
            "is_global": True,
        },
        {
            "name": "Pallof Press",
            "equipment": "Cable",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "Core,Obliques",
            "instructions": "Cable at chest height to side, press straight out and back in, resist rotation throughout",
            "is_global": True,
        },
        {
            "name": "Ab Scissors",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "",
            "instructions": "Lie on back, alternate raising and lowering legs in scissor pattern",
            "is_global": True,
        },
        {
            "name": "Hollow Hold",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "Core",
            "instructions": "Press lower back into floor, extend arms and legs, hold hollow body position",
            "is_global": True,
        },
        {
            "name": "Dead Bug",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "Core",
            "instructions": "Lower back pressed down, alternate extending opposite arm and leg, do not let back arch",
            "is_global": True,
        },
        {
            "name": "Decline Sit Up",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "",
            "instructions": "On decline bench with feet anchored, perform full sit up through complete range of motion",
            "is_global": True,
        },
        {
            "name": "Mountain Climber",
            "equipment": "Bodyweight",
            "primary_muscle": "Abdominals",
            "secondary_muscles": "Core,Cardio",
            "instructions": "Plank position, drive knees to chest alternately keeping hips level",
            "is_global": True,
        },
        # ── CARDIO / CONDITIONING ──────────────────────────
        {
            "name": "Burpee",
            "equipment": "Bodyweight",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Cardio",
            "instructions": "Drop to push up position, perform push up, jump feet in and explode up",
            "is_global": True,
        },
        {
            "name": "Jump Squat",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes,Calves",
            "instructions": "Squat to parallel then explosively jump, land soft and immediately squat again",
            "is_global": True,
        },
        {
            "name": "Box Jump",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes,Calves",
            "instructions": "Swing arms, jump onto box landing softly in squat, stand fully, step down",
            "is_global": True,
        },
        {
            "name": "Rowing Machine",
            "equipment": "Machine",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Back,Legs",
            "instructions": "Drive with legs first, lean back, then pull handle to lower chest — legs, body, arms on the pull",
            "is_global": True,
        },
        {
            "name": "Thruster",
            "equipment": "Barbell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Shoulders,Quadriceps",
            "instructions": "Front squat into overhead press in one fluid motion, drive out of squat into press",
            "is_global": True,
        },
        {
            "name": "Thruster",
            "equipment": "Dumbbell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Shoulders,Quadriceps",
            "instructions": "Dumbbell front squat into overhead press in one fluid motion",
            "is_global": True,
        },
        {
            "name": "Jump Rope",
            "equipment": "Bodyweight",
            "primary_muscle": "Calves",
            "secondary_muscles": "Cardio",
            "instructions": "Stay on balls of feet, keep elbows at sides, consistent rhythm",
            "is_global": True,
        },
        {
            "name": "Battle Ropes",
            "equipment": "Cable",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Core,Cardio",
            "instructions": "Alternate or simultaneous waves, stay in athletic stance with slight knee bend",
            "is_global": True,
        },
        {
            "name": "Wall Sit",
            "equipment": "Bodyweight",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "",
            "instructions": "Back flat against wall, thighs parallel to floor, hold position",
            "is_global": True,
        },
        # ── OLYMPIC / POWER ────────────────────────────────
        {
            "name": "Clean and Jerk",
            "equipment": "Barbell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Shoulders,Legs",
            "instructions": "Pull bar explosively to shoulders then drive overhead, two movement phases",
            "is_global": True,
        },
        {
            "name": "Trap Bar Deadlift",
            "equipment": "Barbell",
            "primary_muscle": "Posterior Chain",
            "secondary_muscles": "Quadriceps,Glutes,Back",
            "instructions": "Stand inside trap bar, hinge and grip handles, drive through floor — more quad-dominant than conventional",
            "is_global": True,
        },
        {
            "name": "Power Clean",
            "equipment": "Barbell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Legs,Back",
            "instructions": "Explosively pull bar from floor to shoulder rack position, catch in partial squat",
            "is_global": True,
        },
        {
            "name": "Hang Clean",
            "equipment": "Barbell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Legs,Back",
            "instructions": "Start from hang position above knees, explosively pull bar to shoulder rack position",
            "is_global": True,
        },
        {
            "name": "Snatch",
            "equipment": "Barbell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Shoulders,Legs",
            "instructions": "Pull bar from floor to overhead in one explosive motion, catch in overhead squat",
            "is_global": True,
        },
        # ── KETTLEBELL ─────────────────────────────────────
        {
            "name": "Kettlebell Swing",
            "equipment": "Kettlebell",
            "primary_muscle": "Glutes",
            "secondary_muscles": "Hamstrings,Core",
            "instructions": "Hinge at hips, drive hips forward explosively to swing kettlebell to chest height",
            "is_global": True,
        },
        {
            "name": "Kettlebell Snatch",
            "equipment": "Kettlebell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Shoulders,Core",
            "instructions": "Swing kettlebell back between legs then explosively drive hips to pull it overhead in one motion",
            "is_global": True,
        },
        {
            "name": "Turkish Get-Up",
            "equipment": "Kettlebell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Core,Shoulders",
            "instructions": "From lying to standing with kettlebell locked overhead the entire time, reverse to return",
            "is_global": True,
        },
        {
            "name": "Kettlebell Clean",
            "equipment": "Kettlebell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Legs,Back",
            "instructions": "Pull kettlebell explosively from swing to rack position at shoulder",
            "is_global": True,
        },
        {
            "name": "Kettlebell Press",
            "equipment": "Kettlebell",
            "primary_muscle": "Shoulders",
            "secondary_muscles": "Triceps,Core",
            "instructions": "Press kettlebell overhead from rack position, keep core braced",
            "is_global": True,
        },
        # ── FUNCTIONAL ─────────────────────────────────────
        {
            "name": "Farmers Walk",
            "equipment": "Dumbbell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Forearms,Core",
            "instructions": "Hold heavy dumbbells at sides, walk with upright posture and controlled steps",
            "is_global": True,
        },
        {
            "name": "Renegade Row",
            "equipment": "Dumbbell",
            "primary_muscle": "Upper Back",
            "secondary_muscles": "Core,Biceps",
            "instructions": "Plank position with hands on dumbbells, row one dumbbell to hip while stabilizing with other arm",
            "is_global": True,
        },
        {
            "name": "Farmers Walk",
            "equipment": "Kettlebell",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Forearms,Core",
            "instructions": "Hold kettlebells at sides, walk with upright posture",
            "is_global": True,
        },
        {
            "name": "Sled Push",
            "equipment": "Machine",
            "primary_muscle": "Quadriceps",
            "secondary_muscles": "Glutes,Full Body",
            "instructions": "Drive sled forward with powerful leg pushes, lean into handles",
            "is_global": True,
        },
        {
            "name": "Sled Pull",
            "equipment": "Machine",
            "primary_muscle": "Back",
            "secondary_muscles": "Hamstrings",
            "instructions": "Face sled and walk backward pulling with arms and legs",
            "is_global": True,
        },
        {
            "name": "Wall Ball",
            "equipment": "Medicine Ball",
            "primary_muscle": "Full Body",
            "secondary_muscles": "Legs,Shoulders",
            "instructions": "Squat then explode up throwing ball to target on wall, catch and repeat",
            "is_global": True,
        },
    ]

    for ex_data in exercises:
        existing = Exercise.query.filter_by(
            name=ex_data["name"], equipment=ex_data["equipment"]
        ).first()
        if not existing:
            key = f"{ex_data['name']} ({ex_data['equipment']})"
            ex_data["image_url"] = EXERCISE_IMAGES.get(key)
            exercise = Exercise(**ex_data)
            db.session.add(exercise)

    db.session.commit()
    print(f"Seeded {len(exercises)} exercises")
